### ISSUE TITLE
Not working with Thunderbird 31

### ISSUE THREAD

**Issue by andyrozman** [guderkar/MExInt#1]
Hi !
I am using pretty old version of thunderbird (31) and I can't install your plugin... What is minimal version of Thunderbird I could use... and please don't say 52...

Andy

P.S.: Is there possibility to recompile it for my version?

**Comment by guderkar** [comment]
Hello,
It's 38.0 - 45.*. There is nothing to compile the module is pure Javascript + Node.js binary. I'll check if I can lower the version, but I think it won't work.

EDIT: I tested the addon with Thunderbird 31 but it doesn't seem to work well with Addon-SDK which I'm using.

**Comment by andyrozman** [comment]
I tried it with version 44, and I get an error when adding account:

Timestamp: 13/04/17 09:22:21
Error: ReferenceError: mexint is not defined
Source File: javascript:%20mexint
Line: 1

**Comment by guderkar** [comment]
Woah that's weird error. I tried with Thunderbird 44 and it worked fine. I don't have any source file named mexint, not even variable. What happens when you click Add Account? Do you get error message (instantly or with a little delay)? I would need to get my hands on it to find out more...

**Comment by guderkar** [comment]
I tried to add mexint reference to all javascript files, so you can try if the error goes away.

**Comment by guderkar** [comment]
Oh god now I know why u getting that error. When you tried to filter mexint in error console, you typed "mexint" in Code field and evaluated it instead of typing it in Filter field. I just did the same thing, the user interface might be little confusing here :-D. Anyway I would like to find out more about actual error or if you somehow resolved it please let me know :-)

**Comment by guderkar** [comment]
Added support for TB version 30 and higher. Also found out that you might need to enter domain\username to authenticate (thanks to Mario Goljak).
