### ISSUE TITLE
thunderbird 52.5.0 issue

### ISSUE THREAD

**Issue by deda-cro** [guderkar/MExInt#4]
After the latest Thunderbird update to version 52.5.0 extension is not working anymore. :(

**Comment by deda-cro** [comment]
I apologize.
This evening after so many Thunderbird restarts, mails arrived with no problem.
Seems like a false alarm.

I'm taking this opportunity to thank you for you work! ;)

**Comment by guderkar** [comment]
Hi, glad everything is working for you :)
