### ISSUE TITLE
MFA support?

### ISSUE THREAD

**Issue by JonnyTech** [guderkar/MExInt#8]
My company enforces MFA (multi factor authentication) so upon logging in I usually have to enter a code to continue. When adding my exchange account in thunderbird then clicking on the "add account" button, the application hangs. Is there anything that I can do or any logs that I can provide to resolve this issue?

**Comment by JonnyTech** [comment]
The authentication uses OAuth - is this supported or is there an alternative?

**Comment by guderkar** [comment]
Sorry this plugin supports only HTTP Basic and NTLM authentication. I don't have much time to add new features right now.

**Comment by JonnyTech** [comment]
OK, thanks - couldn't find it in the docs.
